import type {
  CareerApplication,
  CareerFeedback,
  CareerJob,
  CareerNotification,
  CareerUser,
} from "../types/career-board";

export const CAREER_SQUADS = [
  "Noon Food",
  "Namshi",
  "Noon Core",
  "Logistics",
  "Fugistics",
  "Everyday Labs",
  "Supermall",
  "Noon Minutes",
] as const;

export const CAREER_JOB_ROLES = [
  "Engineering",
  "Product",
  "Design",
  "Data",
  "Marketing",
  "Operations",
  "Finance",
] as const;

export const CAREER_USERS: CareerUser[] = [
  {
    id: "u1",
    name: "Sarah Al-Rashidi",
    title: "Engineering Manager",
    squad: "Noon Core",
    yearsOfExperience: 9,
    bio: "Engineering leader with a passion for building scalable platforms. Currently managing the Core Platform team, driving our next-gen microservices architecture.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=sarah",
    role: "manager",
    contributions: [
      "Led migration of monolith to microservices (2023)",
      "Shipped Payment 2.0 platform serving 10M+ users",
      "Grew team from 4 to 12 engineers",
      "Introduced SRE practices reducing incidents by 40%",
    ],
    skills: ["System Design", "Kotlin", "Go", "Kubernetes", "Leadership"],
  },
  {
    id: "u2",
    name: "Omar Khalifa",
    title: "Senior Software Engineer",
    squad: "Noon Core",
    yearsOfExperience: 6,
    bio: "Backend engineer focused on high-performance APIs and distributed systems. Passionate about clean code and mentoring junior engineers.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=omar",
    role: "employee",
    managerId: "u1",
    contributions: [
      "Built Search v3 reducing latency by 60%",
      "Designed the catalog indexing pipeline",
      "Mentored 3 junior engineers",
    ],
    skills: ["Java", "Kafka", "Elasticsearch", "Redis", "Spring Boot"],
  },
  {
    id: "u3",
    name: "Lina Mansouri",
    title: "Senior Software Engineer",
    squad: "Noon Core",
    yearsOfExperience: 5,
    bio: "Full-stack engineer with a knack for frontend performance. Led the redesign of the product detail page that improved conversion by 15%.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=lina",
    role: "employee",
    managerId: "u1",
    contributions: [
      "Redesigned PDP improving conversion 15%",
      "Built internal design system used across 4 squads",
      "Reduced app bundle size by 35%",
    ],
    skills: ["React", "TypeScript", "GraphQL", "Node.js", "Next.js"],
  },
  {
    id: "u4",
    name: "Karim Hassan",
    title: "Software Engineer",
    squad: "Noon Core",
    yearsOfExperience: 2,
    bio: "Junior engineer working on the checkout experience. Quick learner with a focus on writing testable, maintainable code.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=karim",
    role: "employee",
    managerId: "u2",
    contributions: [
      "Implemented address autocomplete feature",
      "Added 80% unit test coverage to checkout module",
    ],
    skills: ["React", "JavaScript", "Node.js", "PostgreSQL"],
  },
  {
    id: "u5",
    name: "Nour Abdallah",
    title: "Software Engineer",
    squad: "Noon Core",
    yearsOfExperience: 1,
    bio: "Fresh graduate contributing to the order management system. Enthusiastic about distributed systems and cloud technologies.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=nour",
    role: "employee",
    managerId: "u2",
    contributions: [
      "Integrated third-party logistics API",
      "Built order tracking notification service",
    ],
    skills: ["Python", "FastAPI", "Docker", "React"],
  },
  {
    id: "u6",
    name: "Fatima Al-Zahrawi",
    title: "Product Manager",
    squad: "Noon Food",
    yearsOfExperience: 7,
    bio: "PM leading the Noon Food consumer experience. Obsessed with customer insights and data-driven product decisions.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=fatima",
    role: "manager",
    contributions: [
      "Launched Noon Food in 3 new cities",
      "Drove 200% growth in food delivery orders",
      "Shipped loyalty program with 500K users",
    ],
    skills: ["Product Strategy", "SQL", "Figma", "A/B Testing", "Roadmapping"],
  },
  {
    id: "u7",
    name: "Ahmed Sayed",
    title: "Talent Acquisition Lead",
    squad: "Noon Core",
    yearsOfExperience: 5,
    bio: "Building the best engineering teams at noon. Passionate about diversity, inclusion, and technical hiring excellence.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=ahmed",
    role: "talent_acquisition",
    contributions: [
      "Hired 120+ engineers across 8 squads",
      "Reduced time-to-hire by 30%",
      "Built intern-to-hire pipeline",
    ],
    skills: [
      "Technical Recruiting",
      "HR Systems",
      "Interviewing",
      "Employer Branding",
    ],
  },
  {
    id: "u8",
    name: "Mia Chen",
    title: "Data Scientist",
    squad: "Everyday Labs",
    yearsOfExperience: 4,
    bio: "ML engineer building recommendation systems and personalization models for noon's marketplace.",
    avatarUrl: "https://api.dicebear.com/7.x/personas/svg?seed=mia",
    role: "employee",
    managerId: "u1",
    contributions: [
      "Built product recommendation engine (10% revenue lift)",
      "Launched real-time fraud detection model",
    ],
    skills: ["Python", "PyTorch", "Spark", "MLflow", "SQL"],
  },
];

export const CAREER_JOBS: CareerJob[] = [
  {
    id: "j1",
    title: "Senior Backend Engineer",
    squad: "Noon Core",
    yearsRequired: 5,
    description:
      "Join the Core Platform team to build the backbone of noon's marketplace. You'll work on high-scale distributed systems serving millions of customers across the GCC.",
    postedAt: "2026-02-12T09:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Engineering",
    responsibilities: [
      "Design and build scalable microservices using Java/Go",
      "Optimize database queries and caching strategies",
      "Mentor junior engineers and conduct code reviews",
      "Collaborate with product and design on new features",
    ],
    requirements: [
      "5+ years backend engineering experience",
      "Strong knowledge of distributed systems",
      "Experience with Kafka, Redis, or similar",
      "Bachelor's in CS or equivalent",
    ],
  },
  {
    id: "j2",
    title: "Product Manager - Food",
    squad: "Noon Food",
    yearsRequired: 4,
    description:
      "Lead the consumer-facing product for Noon Food. Define the roadmap, work closely with engineering and design, and drive key metrics for our food delivery platform.",
    postedAt: "2026-02-10T10:00:00Z",
    status: "open",
    postedById: "u6",
    jobRole: "Product",
    responsibilities: [
      "Own the product roadmap for food consumer experience",
      "Conduct user research and translate insights to features",
      "Work with data team on product analytics",
      "Align cross-functional stakeholders on priorities",
    ],
    requirements: [
      "4+ years of product management experience",
      "Experience in e-commerce or food delivery",
      "Strong analytical skills with SQL proficiency",
      "Excellent communication and stakeholder management",
    ],
  },
  {
    id: "j3",
    title: "Frontend Engineer",
    squad: "Namshi",
    yearsRequired: 3,
    description:
      "Build world-class shopping experiences for Namshi, noon's fashion vertical. Work on a React-based storefront serving millions of fashion enthusiasts.",
    postedAt: "2026-02-08T08:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Engineering",
    responsibilities: [
      "Build performant React components and pages",
      "Improve Core Web Vitals and page speed",
      "Collaborate with design on pixel-perfect implementations",
      "Own frontend architecture decisions",
    ],
    requirements: [
      "3+ years React/TypeScript experience",
      "Strong understanding of web performance",
      "Experience with CI/CD pipelines",
      "Eye for detail and design sensibility",
    ],
  },
  {
    id: "j4",
    title: "Data Scientist",
    squad: "Everyday Labs",
    yearsRequired: 3,
    description:
      "Build ML models that power noon's personalization engine. Join Everyday Labs - noon's AI and ML innovation hub - to work on cutting-edge recommender systems.",
    postedAt: "2026-02-05T11:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Data",
    responsibilities: [
      "Develop and deploy recommendation models",
      "Run A/B experiments to validate model improvements",
      "Collaborate with engineering on model serving infrastructure",
      "Analyze large datasets using Spark and SQL",
    ],
    requirements: [
      "3+ years experience in ML or data science",
      "Proficiency in Python and ML frameworks (PyTorch, TF)",
      "Strong statistics and math fundamentals",
      "Experience with big data tools (Spark, Hive)",
    ],
  },
  {
    id: "j5",
    title: "Logistics Operations Manager",
    squad: "Logistics",
    yearsRequired: 6,
    description:
      "Lead last-mile delivery operations across KSA and UAE. Drive efficiency, quality, and cost optimization for noon's delivery network of 5,000+ drivers.",
    postedAt: "2026-02-01T09:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Operations",
    responsibilities: [
      "Manage fleet operations and driver performance",
      "Drive KPIs: on-time delivery, customer satisfaction",
      "Identify and implement process improvements",
      "Lead a team of 10+ operations coordinators",
    ],
    requirements: [
      "6+ years in logistics or supply chain",
      "Experience managing large field teams",
      "Strong analytical and problem-solving skills",
      "Fluent in Arabic and English",
    ],
  },
  {
    id: "j6",
    title: "UX Designer",
    squad: "Supermall",
    yearsRequired: 4,
    description:
      "Design seamless shopping experiences for Supermall, noon's premium marketplace. Own end-to-end design from discovery to delivery.",
    postedAt: "2026-01-28T10:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Design",
    responsibilities: [
      "Lead UX for Supermall consumer journeys",
      "Conduct usability testing and synthesize insights",
      "Create wireframes, prototypes, and final designs in Figma",
      "Partner closely with engineering and product",
    ],
    requirements: [
      "4+ years UX/product design experience",
      "Strong portfolio of shipped consumer products",
      "Expert in Figma and prototyping tools",
      "Experience with design systems",
    ],
  },
  {
    id: "j7",
    title: "Mobile Engineer (iOS)",
    squad: "Noon Minutes",
    yearsRequired: 4,
    description:
      "Build the fastest grocery delivery app in the region. Noon Minutes delivers in under 15 minutes - your code needs to be equally fast.",
    postedAt: "2026-01-25T08:00:00Z",
    status: "open",
    postedById: "u1",
    jobRole: "Engineering",
    responsibilities: [
      "Build native iOS features in Swift",
      "Optimize app performance and launch time",
      "Collaborate with Android and backend teams",
      "Own the app release process",
    ],
    requirements: [
      "4+ years iOS development in Swift",
      "Deep understanding of UIKit and SwiftUI",
      "Experience with app performance profiling",
      "Knowledge of CI/CD for mobile apps",
    ],
  },
  {
    id: "j8",
    title: "Growth Marketing Manager",
    squad: "Noon Food",
    yearsRequired: 5,
    description:
      "Drive acquisition and retention for Noon Food. Manage multi-channel campaigns and work closely with product on growth loops.",
    postedAt: "2026-01-20T09:00:00Z",
    status: "closed",
    postedById: "u6",
    jobRole: "Marketing",
    responsibilities: [
      "Own user acquisition campaigns across paid channels",
      "Design and execute retention programs",
      "Analyze funnel metrics and optimize CPA",
      "Collaborate with product on referral and loyalty features",
    ],
    requirements: [
      "5+ years growth marketing experience",
      "Experience with food delivery or quick commerce",
      "Proficiency in analytics tools and SQL",
      "Strong copywriting and creative direction skills",
    ],
  },
];

export const CAREER_APPLICATIONS: CareerApplication[] = [
  {
    id: "a1",
    jobId: "j1",
    applicantId: "u8",
    status: "in_review",
    appliedAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "a2",
    jobId: "j3",
    applicantId: "u8",
    status: "applied",
    appliedAt: "2026-02-13T09:30:00Z",
  },
  {
    id: "a3",
    jobId: "j4",
    applicantId: "u4",
    status: "applied",
    appliedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "a4",
    jobId: "j2",
    applicantId: "u5",
    status: "applied",
    appliedAt: "2026-02-16T08:45:00Z",
  },
  {
    id: "a5",
    jobId: "j1",
    applicantId: "u4",
    status: "applied",
    appliedAt: "2026-02-17T09:00:00Z",
  },
];

export const CAREER_NOTIFICATIONS: CareerNotification[] = [
  {
    id: "n1",
    userId: "u1",
    type: "new_application",
    message: "Mia Chen applied for Senior Backend Engineer",
    relatedJobId: "j1",
    relatedApplicantId: "u8",
    read: false,
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "n2",
    userId: "u1",
    type: "new_application",
    message: "Karim Hassan applied for Senior Backend Engineer",
    relatedJobId: "j1",
    relatedApplicantId: "u4",
    read: false,
    createdAt: "2026-02-17T09:00:00Z",
  },
  {
    id: "n3",
    userId: "u8",
    type: "status_changed",
    message: "Your application for Senior Backend Engineer is now In Review",
    relatedJobId: "j1",
    read: false,
    createdAt: "2026-02-15T12:00:00Z",
  },
];

export const CAREER_FEEDBACK: CareerFeedback[] = [
  {
    id: "f1",
    authorId: "u1",
    authorName: "Sarah Al-Rashidi",
    authorTitle: "Engineering Manager",
    targetUserId: "u8",
    rating: 5,
    comment:
      "Mia is an exceptional data scientist. Her recommendation system delivered a measurable revenue lift and she communicates complex ideas clearly to non-technical stakeholders.",
    date: "2026-02-10T09:00:00Z",
  },
  {
    id: "f2",
    authorId: "u2",
    authorName: "Omar Khalifa",
    authorTitle: "Senior Software Engineer",
    targetUserId: "u8",
    rating: 4,
    comment:
      "Great collaborator - Mia's models are well-documented and she's always available to help with integration questions. Would strongly recommend for a senior IC role.",
    date: "2026-02-12T14:00:00Z",
  },
  {
    id: "f3",
    authorId: "u1",
    authorName: "Sarah Al-Rashidi",
    authorTitle: "Engineering Manager",
    targetUserId: "u4",
    rating: 4,
    comment:
      "Karim has grown significantly in the last 6 months. He takes ownership, writes clean code, and is proactive about testing. Strong candidate for a mid-level role.",
    date: "2026-02-08T10:00:00Z",
  },
];

export const SQUAD_UPCOMING_WORK: Record<string, string[]> = {
  "Noon Core": [
    "Payment 3.0 - unified checkout for all noon verticals",
    "Real-time inventory sync across 20 warehouses",
    "Seller onboarding redesign",
  ],
  "Noon Food": [
    "Corporate meal plans feature",
    "AI-powered personalized menus",
    "Restaurant partner dashboard v2",
  ],
  Namshi: [
    "Virtual try-on using AR",
    "Styling recommendations engine",
    "B2B wholesale portal",
  ],
  Logistics: [
    "Route optimization with ML",
    "Drone delivery pilot in Dubai",
    "Fleet electrification program",
  ],
  Fugistics: [
    "Cross-border fulfillment expansion",
    "Automated sorting facility integration",
    "Returns processing overhaul",
  ],
  "Everyday Labs": [
    "Next-gen personalization engine v2",
    "LLM-powered search",
    "Causal ML experimentation platform",
  ],
  Supermall: [
    "Luxury brand onboarding portal",
    "White-glove delivery experience",
    "Premium membership program",
  ],
  "Noon Minutes": [
    "Dark store expansion to 20 new locations",
    "Sub-10-minute delivery pilot",
    "Predictive inventory replenishment",
  ],
};
